name: Run CI Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  checks:
    # Skip the job if the PR is from develop → main
    if: ${{ !(github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'main') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Cache uv wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install dependencies
        run: make install

      - name: Format and lint
        run: make format

      - name: Type check (mypy)
        run: make mypy

      - name: Run tests with coverage
        run: make coverage
